version: '3.1'

volumes:
  cargo-logistic:

services:
  postgres-db:
    image: postgres:16.1-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: db_cargo_logistic
    volumes:
      - cargo-logistic:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  java-app:
    image: st1mul003/cargo-logistic:lasted
    restart: always
    build: .
    ports:
      - "8080:8080"